RHOAIENG-1916:Adding references to ROSA and updating links
opendatahub-io/opendatahub-documentation pull request #167
Opened 2024-01-31 20:02 UTC by syaseen-rh

## Description
Updated the following sections of the managing users and managing resources guide to include references to ROSA, and also replace the _Adding administrative users in OSD_ to the _Adding administrative users in OpenShift_

Managing Users

- modules/cleaning-up-after-deleting-users.adoc

Managing Resources

-    modules/accessing-notebook-servers-owned-by-other-users.adoc
-    modules/accessing-the-jupyter-administration-interface.adoc
-    modules/starting-notebook-servers-owned-by-other-users.adoc
-    modules/stopping-notebook-servers-owned-by-other-users.adoc
## How Has This Been Tested?
Local Upstream build and downstream previews with ccutil.

Upstream Preview:
![ODH-Cleaning up after deleting users](https://github.com/opendatahub-io/opendatahub-documentation/assets/149716269/9f17b228-6bcd-4ed2-b48b-19371ee06b75)
![ODH-Managing-Resources-1](https://github.com/opendatahub-io/opendatahub-documentation/assets/149716269/c2a2b23c-66c5-4360-a8e4-fda409c6d586)
![ODH-Managing-Resources-2](https://github.com/opendatahub-io/opendatahub-documentation/assets/149716269/08e11b53-17f7-4182-b288-2ee3b72d0e58)

Downstream Previews:
[CS-Managing resources.pdf](https://github.com/opendatahub-io/opendatahub-documentation/files/14116607/CS-Managing.resources.pdf)
[CS-Managing users.pdf](https://github.com/opendatahub-io/opendatahub-documentation/files/14116608/CS-Managing.users.pdf)
[SM-Managing resources-preview.pdf](https://github.com/opendatahub-io/opendatahub-documentation/files/14116609/SM-Managing.resources-preview.pdf)
[SM-Managing users.pdf](https://github.com/opendatahub-io/opendatahub-documentation/files/14116611/SM-Managing.users.pdf)

2024-02-01 09:59 UTC, jbyrne-redhat requested changes

2024-02-01 17:58 UTC, syaseen-rh commented on modules/accessing-notebook-servers-owned-by-other-users.adoc
> +* You are part of the OpenShift Dedicated or Red Hat OpenShift Service on AWS (ROSA) administrator group. For more information, see link:{rhoaidocshome}{default-format-url}/installing_and_uninstallin
Addressed in second commit

2024-02-01 17:58 UTC, syaseen-rh commented on modules/stopping-notebook-servers-owned-by-other-users.adoc
> +* See link:{rhoaidocshome}{default-format-url}/installing_and_uninstalling_{url-productname-short}/adding-administrative-users-in-openshift_install[Adding administrative users in OpenShift] for more
Addressed in second commit.

2024-02-01 17:59 UTC, syaseen-rh commented on modules/cleaning-up-after-deleting-users.adoc
> +* If you are using specialized {productname-short} groups, you are part of the administrator group (for example, {oai-admin-group}). If you are not using specialized groups, you are part of the {open
Address in second commit

2024-02-01 17:59 UTC, syaseen-rh commented on modules/cleaning-up-after-deleting-users.adoc
> +* If you are using specialized {productname-short} groups, you are part of the administrator group (for example, {oai-admin-group}). If you are not using specialized groups, you are part of the OpenS
Addressed in second commit

2024-02-01 17:59 UTC, syaseen-rh commented on modules/cleaning-up-after-deleting-users.adoc
> +After removing a user's access to {productname-long} or Jupyter, you must also delete their associated configuration files from OpenShift.
Addressed in second commit

2024-02-01 17:59 UTC, syaseen-rh commented on modules/cleaning-up-after-deleting-users.adoc
>  After removing a user's access to {productname-long} or Jupyter, you must also delete their associated configuration files from {openshift-platform}.
Addressed in second commit

2024-02-01 17:59 UTC, syaseen-rh commented on modules/accessing-the-jupyter-administration-interface.adoc
> +* You are part of the OpenShift Dedicated or Red Hat OpenShift Service on AWS (ROSA) administrator group. See link:{rhoaidocshome}{default-format-url}/installing_and_uninstalling_{url-productname-sho
Addressed in second commit

2024-02-01 18:01 UTC, syaseen-rh commented on modules/stopping-notebook-servers-owned-by-other-users.adoc
>  * See link:{rhoaidocshome}{default-format-url}/installing_and_uninstalling_{url-productname-short}/adding-administrative-users-for-{openshift-platform-url}_install[Adding administrative users for {op
Addressed in 3rd and 4th commit. Added separate conditions for upstream/SM and CS.

2024-02-02 09:50 UTC, jbyrne-redhat approved these changes
Looks good, @syaseen-rh!

2024-02-02 14:12 UTC, merged