odh-3274 update the getting started guide
opendatahub-io/opendatahub-documentation pull request #303
Opened 2024-06-04 16:31 UTC by MelissaFlinn

2024-06-04 18:52 UTC, grainnejenningsRH requested changes

2024-06-04 18:52 UTC, grainnejenningsRH commented on modules/creating-a-data-science-project.adoc
> +To implement a data science workflow, you must create a project. In OpenShift, a project is a Kubernetes namespace with additional annotations, and is the central method by which access to resources
Could simplify/make this section more active:

- 'and is the central method by which access to resources for regular users is managed' > 'the main way that you can manage user access to resources.'
- 'A project organizes your data science work in one place, keeping your content in isolation while also allowing collaboration with other developers and data scientists in your organization' > 'A project organizes your data science work in one place where you can collaborate with other developers and data scientists in your organization'

2024-06-04 18:52 UTC, grainnejenningsRH commented on modules/creating-a-data-science-project.adoc
> +* Workbenches for working with and processing the data, and for developing models.
Can remove 'the' before 'data'.

2024-06-04 18:52 UTC, grainnejenningsRH commented on modules/creating-a-data-science-project.adoc
> +. In the *Create a data science project* dialog, enter a display *name* for your project.
Capitalize '*name*'.

2024-06-04 18:52 UTC, grainnejenningsRH commented on modules/creating-a-data-science-project.adoc
>  . Optional: Edit the *resource name* for your data science project. The resource name must consist of lowercase alphanumeric characters, '-', and must start and end with an alphanumeric character.
I know this one is legacy/preexisting, but can also capitalize *resource name* here.

2024-06-04 18:52 UTC, grainnejenningsRH commented on modules/creating-a-project-workbench.adoc
> +When you create a workbench, you specify an image (an IDE, packages, and other dependencies). You can also configure data connections, cluster storage, add container storage.
Looks like there's an 'and' needed before 'add container storage'.

2024-06-04 18:52 UTC, grainnejenningsRH commented on modules/creating-a-project-workbench.adoc
> +* To create data connections to your existing S3-compatible storage buckets, you need the following credential information for the storage buckets:
If this is optional, could make the wording a bit more parallel to the other prereqs:

'If you need to create data connections to your existing S3-compatible storage buckets, you have the following credential information:'

2024-06-04 18:52 UTC, grainnejenningsRH commented on modules/creating-a-project-workbench.adoc
> +{productname-short} stores the credentials as Kubernetes secrets in a protected namespace if you select "secret" when you add the variable.
For consistency, can capitalize and bold 'secret' instead of using double quotes.

2024-06-04 18:52 UTC, grainnejenningsRH commented on modules/creating-a-project-workbench.adoc
> +** *Use existing persistent storage* to reuse existing storage and select the storage from the Persistent storage list.
Bold 'Persistent storage'.

2024-06-04 18:52 UTC, grainnejenningsRH commented on modules/creating-a-project-workbench.adoc
> +.. Optionally, you can add a data connection to your workbench.  A data connection is a resource that contains the configuration parameters needed to connect to a data source or an object storage buc
Double space before 'A data connection'

2024-06-04 18:52 UTC, grainnejenningsRH commented on modules/creating-a-project-workbench.adoc
> +In the Data connections section, select the *Use a data connection* checkbox.
Bold 'Data connections'.

2024-06-04 18:52 UTC, grainnejenningsRH commented on modules/creating-a-workbench-select-ide.adoc
> +A workbench is an isolated area where you can examine and work with ML models. You can also work with data and run programs, for example to prepare and clean data. While a workbench is not required i
- Add comma after first 'for example'.
- Could cut the longer 3rd sentence down a bit:

'While a workbench is not required if, for example, you only want to service an existing model, one is needed for most data science workflow tasks, such as writing code to process data, or training a model.'

2024-06-04 18:52 UTC, grainnejenningsRH commented on modules/creating-a-workbench-select-ide.adoc
> +The IDEs are based on a server-client architecture. Each IDE provides a server that runs in a container on the OpenShift cluster, while the user interface (the client) is displayed in your web browse
Double space before 'This architecture'

2024-06-04 18:52 UTC, grainnejenningsRH commented on modules/logging-in.adoc
> +After you install {productname-short}, log in to the {productname-short} dashboard so that you can set up your develop and deploy environment.
Is 'develop and deploy' correct here, or should we have 'development and deployment'?

2024-06-04 18:52 UTC, grainnejenningsRH commented on modules/logging-in.adoc
> +** If you are a data scientist, data engineer, or ML engineer, your administrator must provide you with the {productname-short} instance URL, for example, `https://rhods-dashboard-redhat-oai-applicat
Needs a full stop at end of line.

2024-06-04 18:52 UTC, grainnejenningsRH commented on modules/logging-in.adoc
> +. Click the name of your identity provider, for example, `GitHub`,`Google`, or your company's single-sign on method.
'single-sign on' > 'single sign-on'

2024-06-04 18:52 UTC, grainnejenningsRH commented on modules/next-steps-getting-started.adoc
> +Learn how to access your workbench IDE (JupyterLab, code-sever, or Rstudio Server).
- 'code-sever' > 'code-server'
- 'Rstudio' > 'RStudio'

2024-06-04 18:52 UTC, grainnejenningsRH commented on modules/next-steps-getting-started.adoc
> +Enhance your data science projects on {productname-short} by building portable machine learning (ML) workflows with data science pipelines, by using Docker containers. Use pipelines  for continuous r
Double space before 'for continuous'.

2024-06-04 18:52 UTC, grainnejenningsRH commented on modules/next-steps-getting-started.adoc
> +The {productname-long} service supports model deployment options for hosting the model on Red Hat OpenShift Dedicated or Red Hat Openshift Service on AWS for integration into an external application
Needs a full stop at end of line.

2024-06-04 18:52 UTC, grainnejenningsRH commented on modules/next-steps-getting-started.adoc
> +For the selected category, you can apply additional options to filter the available resources. For example, you can filter by type, such as how-to articles, quick starts, tutorials; these resources p
Looks like an 'and' or 'or' is needed before 'tutorials'.

2024-06-04 18:52 UTC, grainnejenningsRH commented on modules/overview-for-getting-started.adoc
> +{productname-long} is an artificial intelligence (AI) platform that provides tools to rapidly train, serve, and monitor machine learning (ML) models on site, in the public cloud, or at the edge.
on site > onsite

2024-06-04 18:52 UTC, grainnejenningsRH commented on modules/overview-for-getting-started.adoc
> +You can deploy {productname-short} on any (supported version) of OpenShift, whether on-premise, in the cloud, or in disconnected environments. For details on supported versions, see link:https://acce
Can remove brackets around 'supported version'.

2024-06-04 18:52 UTC, grainnejenningsRH commented on modules/overview-for-getting-started.adoc
> +* Defining your business problem and setting goals to solve the problem.
Could replace 'the problem' with 'it'.

2024-06-04 18:52 UTC, grainnejenningsRH commented on modules/overview-for-getting-started.adoc
> +* Train models for your business use case by tuning model parameters based on your set of training data. In practice, data scientists train a range of models, and compare performance while considerin
trade-offs > tradeoffs

2024-06-04 18:52 UTC, grainnejenningsRH commented on modules/overview-for-getting-started.adoc
> +This guide assumes you are familiar with data science and ML Ops concepts. This guide describes the following tasks to get you started using {productname-short}:
Suggestions:

- Replace the second 'This guide' with 'it' to avoid repetition.
- Add 'with' before 'using'.

2024-06-04 20:01 UTC, MelissaFlinn commented on modules/about-workbench-images.adoc
> +Important
yes

2024-06-04 20:01 UTC, MelissaFlinn commented on modules/about-workbench-images.adoc
> +To provide a consistent, stable platform for your model development, all provided workbench images contain the same version of Python. Workbench images available on OpenShift AI are pre-built and rea
added qualifiers - many/most

2024-06-05 08:25 UTC, grainnejenningsRH commented on modules/about-workbench-images.adoc
> +a| With the code-server notebook image, which is an open source web version of VS Code, you can customize your notebook environment to meet your needs using a variety of extensions to add new languag
Comment added offline RE: VS Code references.

2024-06-05 08:26 UTC, grainnejenningsRH commented on modules/about-workbench-images.adoc
> -See link:https://posit.co/products/open-source/rstudio-server/[the RStudio Server site] for more information. +
Just a check - does removing these '+' symbols affect the formatting of the text within the table? I think these were there to force new lines.

2024-06-05 12:52 UTC, merged