ENG-12821: Updates to describe ipywidgets
opendatahub-io/opendatahub-documentation pull request #532
Opened 2024-11-11 19:02 UTC by bredamc

ENG-12821: Updates to describe ipywidgets

2024-11-12 11:09 UTC, ChristianZaccaria reviewed
Looks amazing, thanks Breda!

Two things to mention:

- Something else that we could add (not necessary), is that the `view_clusters()` lists all the RayClusters in the user's namespace/project. However, an admin can explicitly provide a namespace as an argument i.e.,

  ```
  view_clusters("project-1-namespace")
  ```
  This would list the RayClusters in that namespace for the admin. For users, this would likely fail as they would only have access to their own project's namespace.

- We have this [3_widget_example.ipynb](https://github.com/project-codeflare/codeflare-sdk/blob/main/demo-notebooks/guided-demos/3_widget_example.ipynb) notebook where we will be adding all new widgets to. - This is a notebook to simply show the user all the UI widgets that are available for them.

2024-11-12 15:52 UTC, ChristianZaccaria reviewed
/lgtm thank you, awesome work!

2024-11-12 16:16 UTC, eturner24 requested changes

2024-11-12 16:16 UTC, eturner24 commented on modules/managing-ray-clusters-from-within-a-jupyter-notebook.adoc
> +A message is displayed to indicate whether the cluster was successfully created or not.
```suggestion
A message is displayed that indicates whether the cluster was successfully created.
```
Minor nitpick - "whether" implies "or not"

2024-11-12 16:16 UTC, eturner24 commented on modules/managing-ray-clusters-from-within-a-jupyter-notebook.adoc
> +The cluster is deleted immediately, you are not prompted to confirm the deletion.
```suggestion
The cluster is deleted immediately. You are not prompted to confirm the deletion.
```
or
```suggestion
The cluster is deleted immediately; you are not prompted to confirm the deletion.
```

2024-11-12 16:16 UTC, eturner24 commented on modules/managing-ray-clusters-from-within-a-jupyter-notebook.adoc
> +A message is displayed to indicate whether the cluster was successfully deleted or not.
```suggestion
A message is displayed that indicates whether the cluster was successfully deleted.
```

2024-11-12 16:16 UTC, eturner24 commented on modules/managing-ray-clusters-from-within-a-jupyter-notebook.adoc
> +The cluster is deleted immediately, you are not prompted to confirm the deletion.
Same feedback as previous

2024-11-12 16:16 UTC, eturner24 commented on modules/managing-ray-clusters-from-within-a-jupyter-notebook.adoc
> +A message is shown to confirm the deletion, and the corresponding button is no longer shown under the *Select an existing cluster* heading.
> A message is shown to confirm the deletion,

Doesn't this contradict the previous sentence?

2024-11-12 16:16 UTC, eturner24 commented on modules/running-the-demo-notebooks-from-the-codeflare-sdk.adoc
> +Developer Preview software is not supported by Red{nbsp}Hat in any way and is not functionally complete or production-ready.
Should we use an attribute for the company name here?

2024-11-12 16:16 UTC, eturner24 commented on modules/running-the-demo-notebooks-from-the-codeflare-sdk.adoc
> +. In the `2_basic_interactive.ipynb` notebook, ensure that the following Ray cluster authentication code is included after the Ray cluster creation section.
```suggestion
. In the `2_basic_interactive.ipynb` notebook, ensure that the following Ray cluster authentication code is included after the Ray cluster creation section:
```

2024-11-13 09:56 UTC, bredamc commented on modules/managing-ray-clusters-from-within-a-jupyter-notebook.adoc
> +** The Python dependencies for the workload, either in a Ray image or in your own Python Package Index (PyPI) server
These lines are for a list that is at a different level than the list items in lines 17 and 18. The items in this second-level list are all fragments, so no period needed, according to _IBM Style_.

2024-11-13 14:45 UTC, merged